version: '3.8'

services:
  code-review-assistant:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - LLM_PROVIDER=${LLM_PROVIDER}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB:-10}
      - RATE_LIMIT_REQUESTS_PER_MINUTE=${RATE_LIMIT_REQUESTS_PER_MINUTE:-10}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - API_KEY_SALT=${API_KEY_SALT}
      - CORS_ENABLED=${CORS_ENABLED:-false}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - TLS_CERT_FILE=${TLS_CERT_FILE}
      - TLS_KEY_FILE=${TLS_KEY_FILE}
      - TLS_CA_FILE=${TLS_CA_FILE}
    volumes:
      - app-uploads:/app/uploads
      - app-reports:/app/reports
      - app-logs:/app/logs
      - ./ssl:/app/ssl:ro
    env_file:
      - .env.production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
    depends_on:
      - code-review-assistant
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  # Log aggregation
  fluentd:
    image: fluent/fluentd:v1.16-debian-1
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf:ro
      - app-logs:/var/log/app:ro
    ports:
      - "24224:24224"
    environment:
      - FLUENTD_CONF=fluent.conf
    restart: always

volumes:
  app-uploads:
    driver: local
  app-reports:
    driver: local
  app-logs:
    driver: local
  nginx-cache:
    driver: local

networks:
  default:
    name: code-review-prod
    driver: bridge